const Discord = require('discord.js')

exports.run = (bot, message, args, func) => {
let user = message.mentions.users.first() || bot.users.get(args[0]) || message.author 
 /* 
 if (isNaN(args.join(' '))) {
      message.channel.send(`**porfavor pon la ID de un usuario valido**`);
      return;
  }
*/
 if (!user.avatarURL) return message.channel.send( 'Ese usuario no tiene avatar.');
 
 
  const embed = new Discord.RichEmbed()
  .setImage(user.displayAvatarURL)
  .addField(`${user.username}'s Avatar`, '[Descargar](' + user.displayAvatarURL + ')')
  .setThumbnail(user.displayAvatarURL)
  .setFooter(`Avatar generated by ${bot.user.username}`)
  .setColor(0xFFFFFF)
 message.channel.send({embed})
  }
module.exports.config = {
  command: "avatar"
}