const Discord = require('discord.js')
let cooldown = new Set(); 
exports.run = (bot, message, args, func) => {
let user = message.mentions.users.first() || bot.users.get(args[0]) || message.author 

if(cooldown.has(message.author.id)){
   message.channel.send(message.author.username+ " Usa el comando despues de 20 segundos!");
   return;
}
  cooldown.add(message.author.id);
  
  setTimeout(() => {
  cooldown.delete(message.author.id);
}, 20000);
 if (!user.avatarURL) return message.channel.send( 'Ese usuario no tiene avatar.');
 
 
  const embed = new Discord.RichEmbed()
  .setImage(user.displayAvatarURL)
  .addField(`${user.username}'s Avatar`, '[Descargar](' + user.displayAvatarURL + ')')
  .setThumbnail(user.displayAvatarURL)
  .setFooter(`Avatar generated by ${bot.user.username}`)
  .setColor(0x36393e)
 message.channel.send({embed})
  }
module.exports.config = {
  command: "avatar"
}